spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snsapi-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: sns-api
