spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  app:
    jwt:
      secret: ${APP_JWT_SECRET}

  application:
    name: sns-api
